all:
  hosts:
    orion:
      ansible_host: 192.168.100.20
    jellyfin:
     ansible_host: 192.168.100.100
    centreon-prod:
      ansible_host: 192.168.100.7
    technitium-master:
      ansible_host: 192.168.100.5
    docker-node01:
      ansible_host: 192.168.100.8
    docker-node02:
      ansible_host: 192.168.100.11

physical:
  hosts:
    orion:

virtual:
  hosts:
    technitium-master:
    jellyfin:
    centreon-prod:
    docker-node01:
    docker-node02:
    SUSE-Node01:

dns:
  hosts:
    technitium-master:

media:
 hosts:
   jellyfin:

monitoring:
  hosts:
    centreon-prod:
