all:
  hosts:
    orion:
      ansible_host: 192.168.100.20
    jellyfin:
     ansible_host: 192.168.100.100
    SUSE-Node01:
      ansible_host: 192.168.100.10
    centreon-prod:
      ansible_host: 192.168.100.7
    pihole-master:
      ansible_host: 192.168.100.5
    pihole-slave:
      ansible_host: 192.168.100.4
    docker-node01:
      ansible_host: 192.168.100.11

physical:
  hosts:
    orion:

virtual:
  hosts:
    pihole:
    jellyfin:
    centreon-prod:
    docker-node01:
    SUSE-Node01:

dns:
  hosts:
    pihole:

media:
 hosts:
   jellyfin:

monitoring:
  hosts:
    centreon-prod:
