all:
  hosts:
    orion:
      ansible_host: 192.168.100.20
    jellyfin:
     ansible_host: 192.168.100.100
    centreon-prod:
      ansible_host: 192.168.100.7
    technitium-dns:
      ansible_host: 192.168.100.5
    technitium-slave:
      ansible_host: 192.168.100.4
    docker-node01:
      ansible_host: 192.168.100.8
    docker-node02:
      ansible_host: 192.168.100.11

physical:
  hosts:
    orion:

virtual:
  hosts:
    technitium-dns:
    technitium-slave:
    docker-node01:
    docker-node02:
    jellyfin:

dns:
  hosts:
    technitium-dns:
    technitium-slave:

media:
 hosts:
   jellyfin:

monitoring:
  hosts:
    centreon-prod:
