version: "3.9"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Indian/Mauritius
    volumes:
      - ./config:/config
      - /media/tvshows:/tvshows          # Sonarr moves completed episodes here
      - /media/anime:/anime
      - /media/download:/media/download       # qBittorrent stores in this directory
    ports:
      - 8989:8989
    restart: unless-stopped