version: "3.9"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0               # running as root
      - PGID=0
      - TZ=Indian/Mauritius
    volumes:
      - /media/movies:/movies
      - /media/download:/media/download
    ports:
      - 7878:7878
    restart: unless-stopped