---
- name: Homelab
  hosts: all

  roles:
# CORE:
    - role: ssh
      tags: ssh
    - role: system_tweaks
      tags: system_tweaks
    - role: minimal_packages
      tags: minimal_packages
    - role: bashrc
      tags: bashrc
    - role: cron
      tags: cron
    - role: swapfile
      tags: swapfile
    - role: update_motd
      tags: update_motd
    - role: reboot
      tags: reboot
    - role: centreon_monitoring
      tags: centreon_monitoring 
# OPTIONAL:
#    - role: syncthing
#      tags: never, syncthing
    - role: docker
      tags: never, docker
    - role: backup_proxmox
      tags: never, backup_proxmox
    - role: unbound-pihole
      tags: unbound-pihole
